<<<<<<< HEAD
baseURL = "http://localhost:1313"
title = "hicat0x0 blog"
=======
baseURL = "https://HiDomesticCat.github.io/blog/"
title = "我的研究筆記"
>>>>>>> 4cbd9be67009f72ad924b3547b2f50e8e072f533
theme = "hugo-coder"
languageCode = "zh-Hant"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = false

[pagination]
pagerSize = 10

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # author = "hicat0x0"
  # description = "探索前沿科技，分享研究心得 | 資訊安全 • 無線通訊 • 量子電腦 • 雲端技術"
  mainSections = ["posts"]
  # keywords = "資訊安全,網路安全,5G,6G,無線通訊,量子計算,量子密碼學,雲端原生,Kubernetes,DevOps,微服務"
  # info = ["資訊安全","無線通訊","量子計算","網管與雲端"]
  avatarURL = "images/hicat0x0.png"  # commented to avoid missing file 404
  dateFormat = "2006年1月2日"
  since = 2025
  colorScheme = "auto"
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5
  
  # 新增功能
  enableToc = true
  enableTocContent = true
  # customCSS = ["css/custom.css"]
  # customJS = ["js/custom.js"]
  
  # 社交媒體卡片
  # images = ["images/og-image.png"]  # commented to avoid missing file 404
  
  # 閱讀時間
  readingTime = true
  
  # 程式碼高亮主題
  pygmentsStyle = "monokai"
  pygmentsCodeFences = true
  pygmentsUseClasses = false
  pygmentsCodefencesGuessSyntax = true
  
  # 評論系統（可選）
  # disqusShortname = "your-disqus-shortname"
  # utterancesRepo = "your-github-username/your-repo-name"
  # utterancesIssueTerm = "pathname"
  # utterancesTheme = "github-light"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/HiDomesticCat"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/%E5%96%B5-%E6%A9%98-392940248/"

#[[params.social]]
#  name = "Twitter"
#  icon = "fa-brands fa-twitter fa-2x"
#  weight = 3
#  url = "https://twitter.com/your-username"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 4
  url = "/index.xml"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 10
  url = "mailto:hicat0x0@hicat0x0.uk"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[permalinks]
  posts = "/posts/:slug/"

[languages]

  [languages.zh]
    languageName = "繁體中文"
    title = "hicat0x0"
    weight = 1
    contentDir = "content/zh"

    [languages.zh.params]
      author = "于京平 (hicat0x0)"
      description = "資安與無線通訊研究與實作，分享技術筆記、CTF 解題與專題心得 | 資訊安全 • 無線通訊 • 逆向工程 • 雲端原生"
      keywords = "資訊安全,網路安全,CTF,逆向工程,無線通訊,量子電腦,雲端原生,Kubernetes,DevOps,IoT"
      info = ["資訊安全","無線通訊","逆向工程","量子計算","雲端原生"]

    [[languages.zh.menu.main]]
      name = "首頁"
      weight = 1
      url = "zh/"

    [[languages.zh.menu.main]]
      name = "文章"
      weight = 2
      url = "posts/"

    [[languages.zh.menu.main]]
      name = "分類"
      weight = 3
      url = "categories/"

    [[languages.zh.menu.main]]
      name = "標籤"
      weight = 4
      url = "tags/"

    [[languages.zh.menu.main]]
      name = "關於"
      weight = 5
      url = "about/"

    [[languages.zh.menu.main]]
      name = "專案"
      weight = 6
      url = "projects/"

    [[languages.zh.menu.main]]
      name = "聯絡"
      weight = 7
      url = "contact/"

  [languages.en]
    languageName = "English"
    title = "hicat0x0"
    weight = 2
    contentDir = "content/en"

    [languages.en.params]
      author = "hicat0x0"
      # description = "探索前沿科技，分享研究心得 | 資訊安全 • 無線通訊 • 量子電腦 • 雲端技術"
      # keywords = "資訊安全,網路安全,5G,6G,無線通訊,量子計算,量子密碼學,雲端原生,Kubernetes,DevOps,微服務"
      # info = ["資訊安全","無線通訊","量子計算","網管與雲端"]

    [[languages.en.menu.main]]
      name = "Home"
      weight = 1
      url = "en/"

    [[languages.en.menu.main]]
      name = "Posts"
      weight = 2
      url = "posts/"

    [[languages.en.menu.main]]
      name = "Categories"
      weight = 3
      url = "categories/"

    [[languages.en.menu.main]]
      name = "Tags"
      weight = 4
      url = "tags/"

    [[languages.en.menu.main]]
      name = "About"
      weight = 5
      url = "about/"

    [[languages.en.menu.main]]
      name = "Projects"
      weight = 6
      url = "projects/"

    [[languages.en.menu.main]]
      name = "Contact"
      weight = 7
      url = "contact/"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.youtube]
    privacyEnhanced = true

[services]
  [services.googleAnalytics]
    # ID = "UA-XXXXXXXX-X"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "categories"
    weight = 50
  [[related.indices]]
    name = "date"
    weight = 10
